services:
  - mongodb
language: node_js
node_js:
  - "8.10.0"
script:
  - yarn test
before_install:
  - cp .env.sample .env
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"  
